name: anilibria
description: A simple and robust way to interact with Anilibria API. Supports all platforms.
version: 0.8.2
repository: https://github.com/arslee07/anilibria.dart

environment:
    sdk: '>=2.14.4 <3.0.0'

dev_dependencies:
    lints: ^1.0.0

dependencies:
    http: ^0.13.4
